apiVersion: v1
kind: Namespace
metadata:
   name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: development
spec:
  replicas: 2  # Number of replicas for your deployment
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: us-central1-docker.pkg.dev/brian-dev-1222/container-registry/demo-app:latest  # Image name and tag for your application
        ports:
        - containerPort: 8080  # Port on which your application listens
        resources:
          requests:
            cpu: "250m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: development
annotations:
  cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port to which traffic will be forwarded
  type: LoadBalancer  # Type of service (e.g., LoadBalancer, NodePort)
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app-hpa
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app-deployment
  minReplicas: 2  # Minimum number of replicas
  maxReplicas: 3  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
