on: workflow_call

inputs:
  service_account:
    required: true
  workload_identity_provider:
    required: true
  gcp_project_id:
    required: true
  gcp_region:
    required: false
    default: us-central1
  cluster_name:
    required: true
  cluster_namespace:
    required: true
  deployment_name:
    required: true
      
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Authenticate to Cluster
      shell: bash
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud container clusters get-credentials ${{ inputs.cluster_name }} --region ${{ inputs.gcp_region }} --project ${{ inputs.gcp_project_id }}
    - name: K8s Deploy
      shell: bash
      run: |
        kubectl rollout undo deployment ${{ inputs.deployment_name }} --namespace ${{ inputs.cluster_namespace }}
