on: workflow_call

inputs:
  google_application_credentials:
    required: true
  gcp_project_id:
    required: true
  gcp_region:
    required: false
    default: us-central1
  cluster_name:
    required: true
  deployment_name:
    required: true
      
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.google_application_credentials }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Authenticate to Cluster
      shell: bash
      run: |
        gcloud container clusters get-credentials ${{ inputs.cluster_name }} --region ${{ inputs.gcp_region }} --project ${{ inputs.gcp_project_id }}
    - name: K8s Deploy
      shell: bash
      run: |
        kubectl rollout undo deployment ${{ inputs.deployment_name }}
