on: workflow_call

inputs:
  application_url:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run test
      shell: bash
      run: |
        echo "Smoke Test.. ${{ inputs.application_url }}"