on: workflow_call

inputs:
  google_application_credentials:
    required: true
  gcp_project_id:
    required: true
  gcp_region:
    required: false
    default: us-central1
  cluster_name:
    required: true
  cluster_namespace:
    required: true
  k8s_manifest:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.google_application_credentials }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Install auth plugin for kubectl
      shell: bash
      run: |
        gcloud components install gke-gcloud-auth-plugin
    - name: Authenticate to Cluster
      shell: bash
      run: |
        gcloud container clusters get-credentials ${{ inputs.cluster_name }} --region ${{ inputs.gcp_region }} --project ${{ inputs.gcp_project_id }}
    - name: K8s Deploy
      shell: bash
      run: |
        kubectl apply -f ${{ inputs.k8s_manifest }} --namespace=${{ inputs.cluster_namespace }}
    - id: deployment-info
      shell: bash
      run: |
        echo "::set-output name=app_url::$(kubectl get service --namespace ${{ inputs.cluster_namespace }} -o jsonpath='{.items[].status.loadBalancer.ingress[].ip}')"