jobs:
  smoke_test:
    name: Smoke Test Env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test
        run: |
          echo "Smoke Test.. ${{ inputs.application_url }}"