on: workflow_call

inputs:
  google_application_credentials:
    required: true
  gcp_project_id:
    required: true
  artifact_name:
    required: true
  artifact_repo_uri:
    required: false
    default: us-central1-docker.pkg.dev
  artifact_repo_name:
    required: false
    default: container-registry
  dockerfile_context:
    required: false
    default: .
  build_dir:
    required: false
    default: build
      
outputs:
  app_url: ${{ inputs.gcp_project_id }}

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: Build folder
        path: ${{ inputs.build_dir }}
    - name: Checkout code
      uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.google_application_credentials }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Configure Docker CLI
      shell: bash
      run: |
        gcloud auth configure-docker ${{ inputs.artifact_repo_uri }}
    - name: Build and push Docker image to Artifact Registry
      shell: bash
      run: |
        docker build -t ${{ inputs.artifact_repo_uri }}/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repo_name }}/${{ inputs.artifact_name }}:latest ${{ inputs.dockerfile_context }}
        docker push ${{ inputs.artifact_repo_uri }}/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repo_name }}/${{ inputs.artifact_name }}:latest