jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/common/java.yml
        with: 
          java_version: ${{ inputs.java_version }}
          java_distribution: ${{ inputs.java_distribution }}
      - name: Build & Test with Gradle
        run: |
          ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build folder
          path: ${{ inputs.build_dir }}
  sonar-analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Build folder
          path: build
      - uses: ./.github/common/java.yml
        with: 
          java_version: ${{ inputs.java_version }}
          java_distribution: ${{ inputs.java_distribution }}
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarCloud Analyze
        run: |
            ./gradlew sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
