imports:
  - template: ./build.yml
    with:
      java_version: 21
      java_distribution: zulu
      build_dir: build
  - template: ./publish.yml
    with:
      google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
      gcp_project_id: brian-dev-1222
      artifact_repo_uri: us-central1-docker.pkg.dev
      artifact_repo_name: container-registry
      artifact_name: demo-app
      dockerfile_context: .
  - template: ./deploy.yml
    with:
      google_application_credentials: ${{ github.event.inputs.google_application_credentials }}
      gcp_project_id: ${{ github.event.inputs.gcp_project_id }}
      gcp_region: us-central1
      cluster_name: autopilot-cluster-1
      k8s_manifest: deployment.yaml
  - template: ./rollback.yml
    with:
      google_application_credentials: ${{ github.event.inputs.google_application_credentials }}
      gcp_project_id: ${{ github.event.inputs.gcp_project_id }}
      gcp_region: us-central1
      cluster_name: autopilot-cluster-1
      deployment_name: demo-app-deployment

name: Demo CI/CD Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - <<: *build

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - <<: *analyze

  publish:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs:
      - analyze
    if: github.event_name != 'pull_request'

    steps:
      - <<: *pull-build-artifacts
      - <<: *publish

  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - <<: *deploy
        with:
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222

  smoke_dev:
    name: Smoke Test Dev
    needs: deploy_to_dev
    steps:
      - <<: *smoke_test
        with: 
          application_url: $APP_URL

  rollback_dev:
    name: Rollback Dev
    needs: smoke_dev
    if: ${{ failure() }}
    steps:
      - <<: *rollback 

  deploy_to_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - <<: *deploy
        with:
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222

  smoke_prod:
    name: Smoke Test Prod
    needs: deploy_to_prod
    steps:
      - <<: *smoke_test
        with: 
          application_url: $APP_URL

  rollback_prod:
    name: Rollback Prod
    needs: smoke_prod
    if: ${{ failure() }}
    steps:
      - <<: *rollback 
