name: Demo CI/CD Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: build 
        uses: ./.github/actions/gradle-build


  analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: analyze 
        uses: ./.github/actions/gradle-sonar
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/action/docker-push
        with:
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222
          artifact_name: demo-app

  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: ./.github/action/k8s-apply
        with:
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222
          gcp_region: us-central1
          cluster_name: autopilot-cluster-1
          k8s_manifest: deployment.yaml

  smoke_dev:
    name: Smoke Test Dev
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - uses: ./.github/action/smoke-test
        with: 
          application_url: ${{ needs.deploy_to_dev.app_url }}

  rollback_dev:
    name: Rollback Dev
    runs-on: ubuntu-latest
    needs: smoke_dev
    if: ${{ failure() }}
    steps:
      - uses: ./.github/action/k8s-undo-deployment
        with: 
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222
          gcp_region: us-central1
          cluster_name: autopilot-cluster-1
          deployment_name: demo-app-deployment

  deploy_to_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: smoke_dev
    steps:
      - uses: ./.github/action/k8s-apply
        with:
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222
          gcp_region: us-central1
          cluster_name: autopilot-cluster-1
          k8s_manifest: deployment.yaml

  smoke_prod:
    name: Smoke Test Prod
    runs-on: ubuntu-latest
    needs: deploy_to_prod
    steps:
      - uses: ./.github/action/smoke-test
        with: 
          application_url: ${{ needs.deploy_to_prod.app_url }}

  rollback_prod:
    name: Rollback Prod
    runs-on: ubuntu-latest
    needs: smoke_prod
    if: ${{ failure() }}
    steps:
      - uses: ./.github/action/k8s-undo-deployment
        with: 
          google_application_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: brian-dev-1222
          gcp_region: us-central1
          cluster_name: autopilot-cluster-1
          deployment_name: demo-app-deployment