name: Demo CI/CD Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build & Test with Gradle
        run: ./gradlew build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs/demo-0.0.1-SNAPSHOT.jar

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs:
      - build
      
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/demo-0.0.1-SNAPSHOT.jar

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        args: >
          -Dsonar.organization=briananderson1222
          -Dsonar.projectKey=briananderson1222_demo-app
          -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.event_name != 'pull_request'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/demo-0.0.1-SNAPSHOT.jar

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker CLI
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/brian-dev-1222/container-registry/demo-app:latest

  # deploy:
  #   name: Deploy to Kubernetes
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #     - publish
  #   if: github.event_name != 'pull_request'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

      # Add steps to authenticate with Kubernetes cluster and deploy application
