jobs:
  publish:
    name: Publish artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ inputs.google_application_credentials }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker CLI
        run: |
          gcloud auth configure-docker ${{ inputs.artifact_repo_uri }}

      - name: Build and push Docker image to Artifact Registry
        run: |
          docker build -t ${{ inputs.artifact_repo_uri }}/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repo_name }}/${{ inputs.artifact_name }}:latest ${{ inputs.dockerfile_context }}
          docker push ${{ inputs.artifact_repo_uri }}/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repo_name }}/${{ inputs.artifact_name }}:latest