name: Demo Infrastructure Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - terraform-integration
    # paths:
    #   - 'infra/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  GCP_PROJECT_ID: brian-dev-1222
  TF_WORKING_DIR: infra
    
permissions:
  pull-requests: write
    
jobs:
  plan:
    name: Plan Changes
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4
      - id: terraform-plan 
        uses: ./.github/actions/terraform-plan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tf_working_dir: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_gcp_project_id: ${{ env.GCP_PROJECT_ID }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
  apply:
    name: Apply Changes
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - id: terraform-apply 
        uses: ./.github/actions/terraform-apply
        with:
          tf_working_dir: ${{ env.TF_WORKING_DIR }}
        env:
          TF_VAR_gcp_project_id: ${{ env.GCP_PROJECT_ID }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
 
